name: myfin
description: A new Flutter project.

version: 1.2.3+8

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  flutter_bloc: ^8.0.1
  
  intl: any
  provider: ^6.0.4
  shared_preferences: ^2.1.0
  dio: ^5.3.2
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  google_sign_in: ^6.1.0
  firebase_ui_localizations: ^1.3.0
  firebase_ui_auth: ^1.2.2
  firebase_ui_oauth_google: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.0
  bloc_test: ^9.1.1
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  retrofit_generator: ^7.0.8

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/assets/icon/MyFinIcon.png"


flutter:

  uses-material-design: true
  generate: true

  assets:
    - images/

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf


