name: myfin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  flutter_bloc: ^8.0.1
  flutterfire_ui: ^0.4.2
  intl: any
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  retrofit: ^3.3.1
  google_sign_in: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.1
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  retrofit_generator: ^4.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/assets/icon/IconW.png"


flutter:

  uses-material-design: true
  generate: true

  assets:
    - images/


